
(function(){
  if(window.__v311OrderPatch) return; window.__v311OrderPatch=true;
  const GL_TAG='GL_ITEMS', SUP_TAG='SUPPLIER_ORDER';
  const tagRe=name=>new RegExp('\\n?\\[\\['+name+':([\\s\\S]*?)\\]\\]','i');
  function enc(obj){try{return btoa(unescape(encodeURIComponent(JSON.stringify(obj||[]))));}catch(e){return '';}}
  function dec(str){try{return JSON.parse(decodeURIComponent(escape(atob(String(str||'')))));}catch(e){return [];}}
  function readTag(notes,name){const m=String(notes||'').match(tagRe(name));return m?String(m[1]||'').trim():'';}
  function stripTags(notes){return String(notes||'').replace(tagRe(GL_TAG),'').replace(tagRe(SUP_TAG),'').trim();}
  function norm(v){return String(v||'').trim();}
  async function getNextOrderNo(){
    try{const db=window.supabase||window.vpSupabase||window.__vpDb;if(!db)return 'PO-001';const res=await db.from('suppliers').select('order_no').not('order_no','is',null);let max=0;(res.data||[]).forEach(r=>{const m=String(r.order_no||'').match(/^PO-(\d+)$/i);if(m)max=Math.max(max,Number(m[1]||0));});return 'PO-'+String(max+1).padStart(3,'0');}catch(e){return 'PO-001';}
  }
  function ensureSupplierOrderField(){if(document.getElementById('entrySupplierOrderNo'))return;const wrap=document.getElementById('entryOrderWrap');if(wrap)wrap.insertAdjacentHTML('afterend','<label id="entrySupplierOrderWrap"><span>Supplier Order No</span><input class="dark" id="entrySupplierOrderNo" type="text" placeholder="Supplier order / quotation no"></label>');}
  function setOrderLocked(){const el=document.getElementById('entryOrderNo');if(el){el.readOnly=true;el.classList.add('gl-calculated-total');}}
  function setDescriptionFromItems(){try{const items=(typeof window.vardoGlCollectItems==='function')?window.vardoGlCollectItems():[];const first=items.find(x=>x.description)||items[0];const desc=first&&first.description?first.description:(items.length?'Order items':'');['entryDescription','entryDescriptionSelect'].forEach(id=>{const e=document.getElementById(id);if(e&&desc)e.value=desc;});}catch(e){}}
  function loadItems(items){const body=document.getElementById('glItemsBody');if(!body)return;body.innerHTML='';if(Array.isArray(items)&&items.length&&typeof window.vardoGlAddItem==='function')items.forEach(it=>window.vardoGlAddItem(it));else if(typeof window.vardoGlAddItem==='function')window.vardoGlAddItem({});if(typeof window.vardoGlRecalcItems==='function')window.vardoGlRecalcItems();}
  function addPrintButtonIfMissing(){const actions=document.querySelector('#glItemsSection .gl-actions');if(actions&&!actions.querySelector('[data-v311-print]'))actions.insertAdjacentHTML('beforeend','<button type="button" class="ghost" data-v311-print onclick="window.vardoPrintCurrentOrder && window.vardoPrintCurrentOrder()">Print Order</button>');}
  function enhancePrint(){const old=window.vardoPrintCurrentOrder;if(typeof old!=='function'||old.__v311)return;const fn=function(){const supplierOrder=norm(document.getElementById('entrySupplierOrderNo')&&document.getElementById('entrySupplierOrderNo').value);const notes=document.getElementById('entryNotes');const before=notes?notes.value:'';if(notes&&supplierOrder&&!before.includes('Supplier Order No:'))notes.value=(before?before+'\n':'')+'Supplier Order No: '+supplierOrder;const res=old.apply(this,arguments);if(notes)notes.value=before;return res;};fn.__v311=true;window.vardoPrintCurrentOrder=fn;}
  async function afterOpen(args){ensureSupplierOrderField();setOrderLocked();addPrintButtonIfMissing();enhancePrint();const id=args&&args.length?args[0]:null;const forced=args&&args.length>1?args[1]:'';const mode=norm(document.getElementById('entryMode')&&document.getElementById('entryMode').value)||forced;const orderEl=document.getElementById('entryOrderNo'),supEl=document.getElementById('entrySupplierOrderNo'),notesEl=document.getElementById('entryNotes');const raw=notesEl?notesEl.value:'';if(supEl)supEl.value=readTag(raw,SUP_TAG);if(notesEl)notesEl.value=stripTags(raw);loadItems(dec(readTag(raw,GL_TAG)));if(!id&&(mode==='order'||forced==='order')&&orderEl&&!norm(orderEl.value))orderEl.value=await getNextOrderNo();if(orderEl)orderEl.readOnly=true;if(supEl)supEl.disabled=(window.currentRole==='viewer');}
  const oldOpen=window.openEntryModal;if(typeof oldOpen==='function'&&!oldOpen.__v311){const fn=async function(){const args=arguments;const r=await oldOpen.apply(this,args);setTimeout(()=>afterOpen(args),80);setTimeout(()=>afterOpen(args),300);return r;};fn.__v311=true;window.openEntryModal=fn;}
  const oldSave=window.saveEntry;if(typeof oldSave==='function'&&!oldSave.__v311){const fn=async function(){ensureSupplierOrderField();setOrderLocked();if(typeof window.vardoGlRecalcItems==='function')window.vardoGlRecalcItems();const orderEl=document.getElementById('entryOrderNo');const mode=norm(document.getElementById('entryMode')&&document.getElementById('entryMode').value);if(mode==='order'&&orderEl&&!norm(orderEl.value))orderEl.value=await getNextOrderNo();setDescriptionFromItems();const notesEl=document.getElementById('entryNotes');const clean=stripTags(notesEl?notesEl.value:'');const supplierOrder=norm(document.getElementById('entrySupplierOrderNo')&&document.getElementById('entrySupplierOrderNo').value);const items=(typeof window.vardoGlCollectItems==='function')?window.vardoGlCollectItems():[];/* V313: GL Code is optional at Site Request stage. Office can complete it later. */if(notesEl)notesEl.value=clean+(supplierOrder?'\n[['+SUP_TAG+':'+supplierOrder+']]':'')+(items.length?'\n[['+GL_TAG+':'+enc(items)+']]':'');const res=await oldSave.apply(this,arguments);setTimeout(()=>{const m=document.getElementById('entryModal');if(m&&m.classList.contains('show')&&notesEl)notesEl.value=clean;},250);return res;};fn.__v311=true;window.saveEntry=fn;}
  setTimeout(()=>{ensureSupplierOrderField();setOrderLocked();addPrintButtonIfMissing();enhancePrint();},600);
})();
